# https://docs.codecov.com/docs/common-recipe-list#ease-target-coverage

codecov:
  notify:
    require_ci_to_pass: no

coverage:
  precision: 2
  round: nearest
  # https://docs.codecov.com/docs/coverage-configuration#section-range
  range: '70...95'

  status:
    project:
      default:
        # Adjust based on how flaky your tests are.
        # This allows a x% drop from the previous base commit coverage.
        threshold: '1%'
        target: 80%
    patch:
      default:
        only_pulls: true
        threshold: '1%'
        target: 80%
    changes: no

parsers:
  javascript:
    enable_partials: yes

comment: off

github_checks:
    annotations: true
